# Generated by Django 4.0.5 on 2022-06-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userblogpost_delete_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
